name: Build Python Installer for Windows

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Chocolatey
      run: |
        Set-ExecutionPolicy Bypass -Scope Process -Force; [System.Net.ServicePointManager]::SecurityProtocol = [System.Net.ServicePointManager]::SecurityProtocol -bor 3072; iex ((New-Object System.Net.WebClient).DownloadString('https://community.chocolatey.org/install.ps1'))

    - name: Install Visual Studio 2015 Build Tools
      run: |
        choco install visualstudio2015community --package-parameters "--add Microsoft.VisualStudio.Component.VC.Tools.x86.x64 --includeRecommended --includeOptional"
      shell: cmd

    - name: Set up MSVC environment variables for VS2015
      run: |
        call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" amd64

    - name: Download Python source
      run: |
        curl -O https://www.python.org/ftp/python/3.8.20/Python-3.8.20.tgz
        tar -xzf Python-3.8.20.tgz

    - name: Configure and compile Python
      run: |
        cd Python-3.8.20
        PCbuild\build.bat -e -d

    - name: Package the installer
      run: |
        cd Python-3.8.20\PCbuild\amd64
        powershell Compress-Archive -Path . -DestinationPath python-3.8.20-windows.zip

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: Python-Installer
        path: Python-3.8.20/PCbuild/amd64/python-3.8.20-windows.zip
