name: Build Python Installer for Windows on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      MSYSTEM: MINGW64

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up MSYS2
      run: |
        sudo apt-get update
        sudo apt-get install -y curl tar
        curl -L -o msys2-base.tar.xz http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20210725.tar.xz
        sudo tar -xf msys2-base.tar.xz -C /opt
        sudo chown -R $USER:$USER /opt/msys64
        export PATH=/opt/msys64/usr/bin:$PATH
        msys2_shell.cmd -defterm -mingw64 -no-start -full-path -here -c 'pacman -Syu --noconfirm'
        msys2_shell.cmd -defterm -mingw64 -no-start -full-path -here -c 'pacman -S --noconfirm mingw-w64-x86_64-gcc mingw-w64-x86_64-python'

    - name: Compile and package Python
      run: |
        export PATH=/opt/msys64/mingw64/bin:$PATH
        mkdir build
        cd Python-3.8.20
        ./configure
        make -j$(nproc)
        make install DESTDIR=$(pwd)/../build
        cd ../build
        zip -r python-3.8.20-x86_64-windows.zip *

    - name: Upload installer artifact
      uses: actions/upload-artifact@v2
      with:
        name: Python-Installer
        path: build/python-3.8.20-x86_64-windows.zip
