name: Build Python Windows Installer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Download Python Source
        run: |
          Invoke-WebRequest -Uri "https://www.python.org/ftp/python/3.8.20/Python-3.8.20.tgz" -OutFile "Python-3.8.20.tgz"

      - name: Extract Source
        run: |
          tar -xzf Python-3.8.20.tgz

      - name: Configure Python Source
        run: |
          cd Python-3.8.20
          .\configure.bat --enable-optimizations

      - name: Build Python
        run: |
          cd Python-3.8.20
          nmake

      - name: Test Python
        run: |
          cd Python-3.8.20
          nmake test

      - name: Create Installer
        run: |
          cd Python-3.8.20
          # 这里需要创建安装包的命令，具体命令依赖于打包工具，例如Inno Setup或NSIS
          # 假设你有一个名为create_installer.bat的脚本在仓库中
          .\create_installer.bat

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: PythonInstaller
          path: |
            Python-3.8.20/dist/*
