name: Build Python Installer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install build dependencies
      run: |
        choco install visualstudio2019buildtools -y
        choco install nasm -y
        choco install winflexbison3 -y
        choco install strawberryperl -y

    - name: Download Python source
      run: |
        curl -O https://www.python.org/ftp/python/3.8.20/Python-3.8.20.tgz
        tar -xzf Python-3.8.20.tgz

    - name: Compile Python
      run: |
        cd Python-3.8.20
        tools\buildbot\build.bat --no-tkinter -p x64

    - name: Package the installer
      run: |
        cd PCbuild\amd64
        msiexec /a python.msi TARGETDIR=%cd%\PythonInstaller /qn

    - name: Upload installer artifact
      uses: actions/upload-artifact@v2
      with:
        name: Python-Installer
        path: PythonInstaller/*
