name: Build Python Installer for Windows on Linux

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python 3.8
      run: |
        sudo apt-get update
        sudo add-apt-repository ppa:deadsnakes/ppa -y
        sudo apt-get update
        sudo apt-get install -y python3.8 python3.8-venv python3.8-distutils

    - name: Install dependencies
      run: |
        sudo apt-get install -y build-essential mingw-w64
        sudo apt-get install -y curl tar

    - name: Download Python source
      run: |
        curl -O https://www.python.org/ftp/python/3.8.20/Python-3.8.20.tgz
        tar -xzf Python-3.8.20.tgz

    - name: Configure and compile Python
      run: |
        cd Python-3.8.20
        ./configure --host=x86_64-w64-mingw32 --build=x86_64-linux-gnu --prefix=$(pwd)/build --enable-shared
        make -j$(nproc)
        make install

    - name: Package the installer
      run: |
        cd Python-3.8.20/build
        zip -r python-3.8.20-x86_64-windows.zip *

    - name: Upload installer artifact
      uses: actions/upload-artifact@v4
      with:
        name: Python-Installer
        path: Python-3.8.20/build/python-3.8.20-x86_64-windows.zip
