name: Build Python 3.4

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python 3.4 dependencies
      run: |
        choco install -y nasm
        choco install -y strawberryperl
        choco install -y winflexbison3
        choco install -y ninja

    - name: Download Python 3.4 Source Code
      run: |
        curl -O https://www.python.org/ftp/python/3.4.10/Python-3.4.10.tgz
        tar xzf Python-3.4.10.tgz

    - name: Configure and Build
      run: |
        cd Python-3.4.10
        PCbuild\build.bat -e

    - name: Archive Build Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-3.4.10-build
        path: Python-3.4.10\PCbuild\amd64
        
    - name: Display Python Version
      run: Python-3.4.10\PCbuild\amd64\python.exe --version
